import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap-grid.css";
import "bootstrap/dist/css/bootstrap-utilities.css";
import "bootstrap/dist/css/bootstrap-reboot.css";
import "./globals.css";
import { roboto, montserrat, logoFont } from "@/app/fonts";
import { Header } from "@/app/components/Header/Header";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${logoFont.variable} ${montserrat.variable} ${roboto.variable}`}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
